FROM node:24-alpine AS builder
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY . .
RUN pnpm install --frozen-lockfile --no-engine

ENV NEXT_TELEMETRY_DISABLED 1

# Gesamten Workspace bauen
RUN pnpm build

FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

ARG APP_NAME=chat-bot
ENV APP_DIR=${APP_NAME}

COPY --from=builder /app ./

USER nextjs

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["sh", "-c", "pnpm --filter @ais-chat/${APP_DIR} start || pnpm --filter ${APP_DIR} start"]
