FROM node:20-alpine AS builder
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

# Gesamtes Repository kopieren & Abhängigkeiten installieren
COPY . .
RUN pnpm install --frozen-lockfile

ARG APP_NAME=chat-bot
ENV NEXT_TELEMETRY_DISABLED 1

# App (chat-bot oder admin) bauen
RUN pnpm --filter ${APP_NAME} build

# Runner Stage
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

ARG APP_NAME=chat-bot
ENV APP_NAME_ENV=${APP_NAME}

COPY --from=builder /app ./

USER nextjs

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD pnpm --filter ${APP_NAME_ENV} start
