# Build Stage
FROM node:20-alpine AS builder
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/ais-chat-api/package.json ./apps/ais-chat-api/
COPY packages/ ./packages/

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm --filter ais-chat-api build

# Production Stage
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs

COPY --from=builder /app/apps/ais-chat-api/dist ./dist
COPY --from=builder /app/apps/ais-chat-api/node_modules ./node_modules
COPY --from=builder /app/node_modules ./node_modules

USER nestjs

EXPOSE 3000

CMD ["node", "dist/main.js"]
