FROM node:20-alpine AS builder
WORKDIR /app

# PNPM aktivieren
RUN corepack enable && corepack prepare pnpm@latest --activate

# Gesamtes Repository kopieren & Abhängigkeiten installieren
COPY . .
RUN pnpm install --frozen-lockfile

# API bauen
RUN pnpm --filter ais-chat-api build

# Production Stage
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs

COPY --from=builder /app ./

USER nestjs

EXPOSE 3000

CMD ["pnpm", "--filter", "ais-chat-api", "start"]
