FROM node:24-alpine AS builder
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY . .
RUN pnpm install --frozen-lockfile --no-engine

RUN pnpm --filter ais-chat-api build

FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs

COPY --from=builder /app ./

USER nestjs

EXPOSE 3000

CMD ["pnpm", "--filter", "ais-chat-api", "start"]
